// Code generated by github.com/ukfast/sdk-go/pkg/gen/response. DO NOT EDIT.
package ddosx

import "github.com/ukfast/sdk-go/pkg/connection"

// GetDomainArrayResponseBody represents an API response body containing []Domain data
type GetDomainArrayResponseBody struct {
	connection.APIResponseBody

	Data []Domain `json:"data"`
}

// GetDomainResponseBody represents an API response body containing Domain data
type GetDomainResponseBody struct {
	connection.APIResponseBody

	Data Domain `json:"data"`
}

// GetDomainPropertyArrayResponseBody represents an API response body containing []DomainProperty data
type GetDomainPropertyArrayResponseBody struct {
	connection.APIResponseBody

	Data []DomainProperty `json:"data"`
}

// GetDomainPropertyResponseBody represents an API response body containing DomainProperty data
type GetDomainPropertyResponseBody struct {
	connection.APIResponseBody

	Data DomainProperty `json:"data"`
}

// GetRecordArrayResponseBody represents an API response body containing []Record data
type GetRecordArrayResponseBody struct {
	connection.APIResponseBody

	Data []Record `json:"data"`
}

// GetRecordResponseBody represents an API response body containing Record data
type GetRecordResponseBody struct {
	connection.APIResponseBody

	Data Record `json:"data"`
}

// GetWAFArrayResponseBody represents an API response body containing []WAF data
type GetWAFArrayResponseBody struct {
	connection.APIResponseBody

	Data []WAF `json:"data"`
}

// GetWAFResponseBody represents an API response body containing WAF data
type GetWAFResponseBody struct {
	connection.APIResponseBody

	Data WAF `json:"data"`
}

// GetWAFRuleSetArrayResponseBody represents an API response body containing []WAFRuleSet data
type GetWAFRuleSetArrayResponseBody struct {
	connection.APIResponseBody

	Data []WAFRuleSet `json:"data"`
}

// GetWAFRuleSetResponseBody represents an API response body containing WAFRuleSet data
type GetWAFRuleSetResponseBody struct {
	connection.APIResponseBody

	Data WAFRuleSet `json:"data"`
}

// GetWAFRuleArrayResponseBody represents an API response body containing []WAFRule data
type GetWAFRuleArrayResponseBody struct {
	connection.APIResponseBody

	Data []WAFRule `json:"data"`
}

// GetWAFRuleResponseBody represents an API response body containing WAFRule data
type GetWAFRuleResponseBody struct {
	connection.APIResponseBody

	Data WAFRule `json:"data"`
}

// GetWAFAdvancedRuleArrayResponseBody represents an API response body containing []WAFAdvancedRule data
type GetWAFAdvancedRuleArrayResponseBody struct {
	connection.APIResponseBody

	Data []WAFAdvancedRule `json:"data"`
}

// GetWAFAdvancedRuleResponseBody represents an API response body containing WAFAdvancedRule data
type GetWAFAdvancedRuleResponseBody struct {
	connection.APIResponseBody

	Data WAFAdvancedRule `json:"data"`
}

// GetSSLArrayResponseBody represents an API response body containing []SSL data
type GetSSLArrayResponseBody struct {
	connection.APIResponseBody

	Data []SSL `json:"data"`
}

// GetSSLResponseBody represents an API response body containing SSL data
type GetSSLResponseBody struct {
	connection.APIResponseBody

	Data SSL `json:"data"`
}

// GetSSLPrivateKeyArrayResponseBody represents an API response body containing []SSLPrivateKey data
type GetSSLPrivateKeyArrayResponseBody struct {
	connection.APIResponseBody

	Data []SSLPrivateKey `json:"data"`
}

// GetSSLPrivateKeyResponseBody represents an API response body containing SSLPrivateKey data
type GetSSLPrivateKeyResponseBody struct {
	connection.APIResponseBody

	Data SSLPrivateKey `json:"data"`
}

// GetSSLContentArrayResponseBody represents an API response body containing []SSLContent data
type GetSSLContentArrayResponseBody struct {
	connection.APIResponseBody

	Data []SSLContent `json:"data"`
}

// GetSSLContentResponseBody represents an API response body containing SSLContent data
type GetSSLContentResponseBody struct {
	connection.APIResponseBody

	Data SSLContent `json:"data"`
}

// GetACLGeoIPRuleArrayResponseBody represents an API response body containing []ACLGeoIPRule data
type GetACLGeoIPRuleArrayResponseBody struct {
	connection.APIResponseBody

	Data []ACLGeoIPRule `json:"data"`
}

// GetACLGeoIPRuleResponseBody represents an API response body containing ACLGeoIPRule data
type GetACLGeoIPRuleResponseBody struct {
	connection.APIResponseBody

	Data ACLGeoIPRule `json:"data"`
}

// GetACLIPRuleArrayResponseBody represents an API response body containing []ACLIPRule data
type GetACLIPRuleArrayResponseBody struct {
	connection.APIResponseBody

	Data []ACLIPRule `json:"data"`
}

// GetACLIPRuleResponseBody represents an API response body containing ACLIPRule data
type GetACLIPRuleResponseBody struct {
	connection.APIResponseBody

	Data ACLIPRule `json:"data"`
}

// GetCDNRuleArrayResponseBody represents an API response body containing []CDNRule data
type GetCDNRuleArrayResponseBody struct {
	connection.APIResponseBody

	Data []CDNRule `json:"data"`
}

// GetCDNRuleResponseBody represents an API response body containing CDNRule data
type GetCDNRuleResponseBody struct {
	connection.APIResponseBody

	Data CDNRule `json:"data"`
}

// GetHSTSConfigurationArrayResponseBody represents an API response body containing []HSTSConfiguration data
type GetHSTSConfigurationArrayResponseBody struct {
	connection.APIResponseBody

	Data []HSTSConfiguration `json:"data"`
}

// GetHSTSConfigurationResponseBody represents an API response body containing HSTSConfiguration data
type GetHSTSConfigurationResponseBody struct {
	connection.APIResponseBody

	Data HSTSConfiguration `json:"data"`
}

// GetHSTSRuleArrayResponseBody represents an API response body containing []HSTSRule data
type GetHSTSRuleArrayResponseBody struct {
	connection.APIResponseBody

	Data []HSTSRule `json:"data"`
}

// GetHSTSRuleResponseBody represents an API response body containing HSTSRule data
type GetHSTSRuleResponseBody struct {
	connection.APIResponseBody

	Data HSTSRule `json:"data"`
}

// GetWAFLogArrayResponseBody represents an API response body containing []WAFLog data
type GetWAFLogArrayResponseBody struct {
	connection.APIResponseBody

	Data []WAFLog `json:"data"`
}

// GetWAFLogResponseBody represents an API response body containing WAFLog data
type GetWAFLogResponseBody struct {
	connection.APIResponseBody

	Data WAFLog `json:"data"`
}

// GetWAFLogMatchArrayResponseBody represents an API response body containing []WAFLogMatch data
type GetWAFLogMatchArrayResponseBody struct {
	connection.APIResponseBody

	Data []WAFLogMatch `json:"data"`
}

// GetWAFLogMatchResponseBody represents an API response body containing WAFLogMatch data
type GetWAFLogMatchResponseBody struct {
	connection.APIResponseBody

	Data WAFLogMatch `json:"data"`
}
