image: golang:1.11

stages:
- test

go_test:
  stage: test
  before_script:
    - mkdir -p $GOPATH/src/github.com/ukfast
    - cp -r $CI_PROJECT_DIR /go/src/github.com/ukfast
    - cd $GOPATH/src/github.com/ukfast/sdk-go
    - go get -v -t -d ./...
  script:
    - go test ./... -coverprofile cover.out
    - go tool cover -func cover.out
  tags:
    - goclient
    - docker
