// Code generated by github.com/ukfast/sdk-go/pkg/gen/response. DO NOT EDIT.
package draas

import "github.com/ukfast/sdk-go/pkg/connection"

// GetSolutionArrayResponseBody represents an API response body containing []Solution data
type GetSolutionArrayResponseBody struct {
	connection.APIResponseBody

	Data []Solution `json:"data"`
}

// GetSolutionResponseBody represents an API response body containing Solution data
type GetSolutionResponseBody struct {
	connection.APIResponseBody

	Data Solution `json:"data"`
}

// GetBackupResourceArrayResponseBody represents an API response body containing []BackupResource data
type GetBackupResourceArrayResponseBody struct {
	connection.APIResponseBody

	Data []BackupResource `json:"data"`
}

// GetBackupResourceResponseBody represents an API response body containing BackupResource data
type GetBackupResourceResponseBody struct {
	connection.APIResponseBody

	Data BackupResource `json:"data"`
}

// GetBackupServiceArrayResponseBody represents an API response body containing []BackupService data
type GetBackupServiceArrayResponseBody struct {
	connection.APIResponseBody

	Data []BackupService `json:"data"`
}

// GetBackupServiceResponseBody represents an API response body containing BackupService data
type GetBackupServiceResponseBody struct {
	connection.APIResponseBody

	Data BackupService `json:"data"`
}

// GetIOPSTierArrayResponseBody represents an API response body containing []IOPSTier data
type GetIOPSTierArrayResponseBody struct {
	connection.APIResponseBody

	Data []IOPSTier `json:"data"`
}

// GetIOPSTierResponseBody represents an API response body containing IOPSTier data
type GetIOPSTierResponseBody struct {
	connection.APIResponseBody

	Data IOPSTier `json:"data"`
}

// GetFailoverPlanArrayResponseBody represents an API response body containing []FailoverPlan data
type GetFailoverPlanArrayResponseBody struct {
	connection.APIResponseBody

	Data []FailoverPlan `json:"data"`
}

// GetFailoverPlanResponseBody represents an API response body containing FailoverPlan data
type GetFailoverPlanResponseBody struct {
	connection.APIResponseBody

	Data FailoverPlan `json:"data"`
}

// GetComputeResourceArrayResponseBody represents an API response body containing []ComputeResource data
type GetComputeResourceArrayResponseBody struct {
	connection.APIResponseBody

	Data []ComputeResource `json:"data"`
}

// GetComputeResourceResponseBody represents an API response body containing ComputeResource data
type GetComputeResourceResponseBody struct {
	connection.APIResponseBody

	Data ComputeResource `json:"data"`
}

// GetHardwarePlanArrayResponseBody represents an API response body containing []HardwarePlan data
type GetHardwarePlanArrayResponseBody struct {
	connection.APIResponseBody

	Data []HardwarePlan `json:"data"`
}

// GetHardwarePlanResponseBody represents an API response body containing HardwarePlan data
type GetHardwarePlanResponseBody struct {
	connection.APIResponseBody

	Data HardwarePlan `json:"data"`
}

// GetReplicaArrayResponseBody represents an API response body containing []Replica data
type GetReplicaArrayResponseBody struct {
	connection.APIResponseBody

	Data []Replica `json:"data"`
}

// GetReplicaResponseBody represents an API response body containing Replica data
type GetReplicaResponseBody struct {
	connection.APIResponseBody

	Data Replica `json:"data"`
}

// GetBillingTypeArrayResponseBody represents an API response body containing []BillingType data
type GetBillingTypeArrayResponseBody struct {
	connection.APIResponseBody

	Data []BillingType `json:"data"`
}

// GetBillingTypeResponseBody represents an API response body containing BillingType data
type GetBillingTypeResponseBody struct {
	connection.APIResponseBody

	Data BillingType `json:"data"`
}
