// Code generated by github.com/ukfast/sdk-go/pkg/gen/response. DO NOT EDIT.
package account

import "github.com/ukfast/sdk-go/pkg/connection"

// GetContactArrayResponseBody represents an API response body containing []Contact data
type GetContactArrayResponseBody struct {
	connection.APIResponseBody

	Data []Contact `json:"data"`
}

// GetContactResponseBody represents an API response body containing Contact data
type GetContactResponseBody struct {
	connection.APIResponseBody

	Data Contact `json:"data"`
}

// GetCreditArrayResponseBody represents an API response body containing []Credit data
type GetCreditArrayResponseBody struct {
	connection.APIResponseBody

	Data []Credit `json:"data"`
}

// GetCreditResponseBody represents an API response body containing Credit data
type GetCreditResponseBody struct {
	connection.APIResponseBody

	Data Credit `json:"data"`
}

// GetDetailsArrayResponseBody represents an API response body containing []Details data
type GetDetailsArrayResponseBody struct {
	connection.APIResponseBody

	Data []Details `json:"data"`
}

// GetDetailsResponseBody represents an API response body containing Details data
type GetDetailsResponseBody struct {
	connection.APIResponseBody

	Data Details `json:"data"`
}

// GetInvoiceArrayResponseBody represents an API response body containing []Invoice data
type GetInvoiceArrayResponseBody struct {
	connection.APIResponseBody

	Data []Invoice `json:"data"`
}

// GetInvoiceResponseBody represents an API response body containing Invoice data
type GetInvoiceResponseBody struct {
	connection.APIResponseBody

	Data Invoice `json:"data"`
}

// GetInvoiceQueryArrayResponseBody represents an API response body containing []InvoiceQuery data
type GetInvoiceQueryArrayResponseBody struct {
	connection.APIResponseBody

	Data []InvoiceQuery `json:"data"`
}

// GetInvoiceQueryResponseBody represents an API response body containing InvoiceQuery data
type GetInvoiceQueryResponseBody struct {
	connection.APIResponseBody

	Data InvoiceQuery `json:"data"`
}
