// Code generated by model_paginated_gen. DO NOT EDIT.
package account

import "github.com/ukfast/sdk-go/pkg/connection"

// PaginatedContact represents a paginated collection of Contact
type PaginatedContact struct {
	*connection.PaginatedBase

	Items []Contact
}

// NewPaginatedContact returns a pointer to an initialized PaginatedContact struct
func NewPaginatedContact(getFunc connection.PaginatedGetFunc, parameters connection.APIRequestParameters, pagination connection.APIResponseMetadataPagination, items []Contact) *PaginatedContact {
	return &PaginatedContact{
		Items:         items,
		PaginatedBase: connection.NewPaginatedBase(parameters, pagination, getFunc),
	}
}

// PaginatedInvoice represents a paginated collection of Invoice
type PaginatedInvoice struct {
	*connection.PaginatedBase

	Items []Invoice
}

// NewPaginatedInvoice returns a pointer to an initialized PaginatedInvoice struct
func NewPaginatedInvoice(getFunc connection.PaginatedGetFunc, parameters connection.APIRequestParameters, pagination connection.APIResponseMetadataPagination, items []Invoice) *PaginatedInvoice {
	return &PaginatedInvoice{
		Items:         items,
		PaginatedBase: connection.NewPaginatedBase(parameters, pagination, getFunc),
	}
}
